DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  username VARCHAR(64) DEFAULT NULL,
  password VARCHAR(16) DEFAULT NULL,
  last_name VARCHAR(64) NOT NULL,
  first_name VARCHAR(64) NOT NULL
);