DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS FOOD;

CREATE TABLE USER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  username VARCHAR(64) DEFAULT NULL,
  password VARCHAR(16) DEFAULT NULL,
  last_name VARCHAR(64) NOT NULL,
  first_name VARCHAR(64) NOT NULL
);

CREATE TABLE FOOD
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    libelle VARCHAR(64) DEFAULT NULL
);

INSERT INTO USER VALUES (999,'user','pwd','lastname','firstName');


INSERT INTO FOOD VALUES (999,'japonais');
INSERT INTO FOOD VALUES (1000,'italien');